title: Robotka
author: RoboticsBrno
email: info@robotikabrno.cz
description: > # this means to ignore newlines until "baseurl:"
    Robotka pro Robotický tábor

twitter_username: RobotikaBrno
github_username:  RoboticsBrno

sass:
    style: compressed

collections:
  guides:
      output: true
  coding:
      output: true
  inspiration:
      output: true
  assignments:
      output: true

#plugins:
#   - jekyll-minifier

kramdown:
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        tab_width: 4
        span:
            line_numbers: false
        block:
            line_numbers: true
            start_line: 1

mini_magick:
    thumbnail:
        source: img/guides/original
        destination: thumb/img/guides
        resize: "700x400"
      
    medium:
        source: img/guides/original
        destination: img/guides/
        resize: "1500x1000"

    gal_thumb:
        source: img/gallery/original
        destination: thumb/img/gallery
        resize: "600x400"
    
    gal_medium:
        source: img/gallery/original
        destination: img/gallery
        resize: "1500x1000"

# Google Analytics
google_analytics: UA-172441283-1
